version: 1

update_configs:
  - package_manager: "docker"
    directory: "/"
    update_schedule: "weekly"
    default_assignees:
      - "jeffcook"
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"
    default_assignees:
      - "jeffcook"
